### ISSUE TITLE
is there a way to import this for all files without importing on each file?

### ISSUE THREAD

**Issue by mrkaspa** [whatyouhide/short_maps#12]

**Comment by whatyouhide** [comment]
@mrkaspa hey there, thanks for the issue. There is no simple way to import this on all files without specifically using `import` in each file, but it's not a short_maps thing: it's rather an Elixir design decision. Explicitly `import`ing modules makes code easier to read because for each module/file you know exactly what's imported and what isn't, making things less "magic" :)

Hope this answered your issue, feel free to ping again if something isn't clear :) 👍

**Comment by mrkaspa** [comment]
Thx yeah I was wondering if there were a way to do it
